name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add destination repository as remote
        run: git remote add destination https://$DESTINATION_REPO_PAT@github.com/GUGALU/projeto-integrador-front.git
        env:
          DESTINATION_REPO_PAT: ${{ secrets.DEPLOY }}

      - name: Push to destination repository
        run: |
          git push destination main --force
