name: Push org
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup-permission
      run: |
        git config --global --add safe.directory /github/workspace
    - name: mirror
      id: mirror
      uses: bridgelightcloud/github-mirror-action@v1
      with:
        origin: https://github.com/GUGALU/projeto-integrador-front.git
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
