name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up SSH for GitHub
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Push to the mirror repository
      env:
        REPO_TOKEN: ${{ secrets.DEPLOY }}
      run: |
        git remote add mirror https://github.com/GUGALU/projeto-integrador-front.git
        git push --mirror mirror
